SIM ?= icarus
TOPLEVEL_LANG ?= verilog
VERILOG_SOURCES += $(PWD)/../build/verilog/regfile.v
or:
	$(MAKE) sim MODULE=test_mkstage1 TOPLEVEL=regfile
include $(shell cocotb-config --makefile)/Makefile.sim